DROP TABLE IF EXISTS "user_payments";
DROP TYPE IF EXISTS "paid_status";
DROP TABLE IF EXISTS "requests";
DROP TYPE IF EXISTS "approval_status";
DROP TABLE IF EXISTS "clients";
DROP TYPE IF EXISTS "payment_types";
DROP TABLE IF EXISTS "users_permissions";
DROP TABLE IF EXISTS "permissions";
DROP TABLE IF EXISTS "users";