// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ApprovalStatus string

const (
	ApprovalStatusPending  ApprovalStatus = "pending"
	ApprovalStatusApproved ApprovalStatus = "approved"
	ApprovalStatusRejected ApprovalStatus = "rejected"
)

func (e *ApprovalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalStatus(s)
	case string:
		*e = ApprovalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalStatus: %T", src)
	}
	return nil
}

type NullApprovalStatus struct {
	ApprovalStatus ApprovalStatus
	Valid          bool // Valid is true if ApprovalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalStatus), nil
}

type PaidStatus string

const (
	PaidStatusNotPaid PaidStatus = "not_paid"
	PaidStatusPaid    PaidStatus = "paid"
)

func (e *PaidStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaidStatus(s)
	case string:
		*e = PaidStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaidStatus: %T", src)
	}
	return nil
}

type NullPaidStatus struct {
	PaidStatus PaidStatus
	Valid      bool // Valid is true if PaidStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaidStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaidStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaidStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaidStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaidStatus), nil
}

type PaymentTypes string

const (
	PaymentTypesMasterCard PaymentTypes = "master_card"
	PaymentTypesVisa       PaymentTypes = "visa"
	PaymentTypesMpesa      PaymentTypes = "mpesa"
)

func (e *PaymentTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentTypes(s)
	case string:
		*e = PaymentTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentTypes: %T", src)
	}
	return nil
}

type NullPaymentTypes struct {
	PaymentTypes PaymentTypes
	Valid        bool // Valid is true if PaymentTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentTypes) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentTypes), nil
}

type Client struct {
	ID                   int64          `json:"id"`
	Name                 string         `json:"name"`
	Email                string         `json:"email"`
	Phone                string         `json:"phone"`
	AccountNumber        sql.NullString `json:"account_number"`
	PreferredPaymentType PaymentTypes   `json:"preferred_payment_type"`
	CreatedbyID          string         `json:"createdby_id"`
}

type DarajaToken struct {
	ID          int64     `json:"id"`
	AccessToken string    `json:"access_token"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type Permission struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedbyID string `json:"createdby_id"`
}

type Request struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	// Payment Status can be PENDING or RESOLVED
	Status       ApprovalStatus `json:"status"`
	Amount       int64          `json:"amount"`
	PaidToID     int64          `json:"paid_to_id"`
	CreatedbyID  string         `json:"createdby_id"`
	ApprovedbyID string         `json:"approvedby_id"`
	CreatedAt    time.Time      `json:"created_at"`
	ApprovedAt   time.Time      `json:"approved_at"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type UserPayment struct {
	ID        int64         `json:"id"`
	RequestID sql.NullInt64 `json:"request_id"`
	ClientID  sql.NullInt64 `json:"client_id"`
	CreatedAt time.Time     `json:"created_at"`
	Status    PaidStatus    `json:"status"`
}

type UsersPermission struct {
	ID           int64  `json:"id"`
	UserID       string `json:"user_id"`
	PermissionID int64  `json:"permission_id"`
	CreatedbyID  string `json:"createdby_id"`
}
