// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPayment(ctx context.Context, arg CreateUserPaymentParams) (UserPayment, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UsersRole, error)
	DeleteClient(ctx context.Context, id int64) error
	DeletePermission(ctx context.Context, id int64) error
	DeleteRequest(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserPayment(ctx context.Context, id int64) error
	DeleteUserRole(ctx context.Context, id int64) error
	GetClient(ctx context.Context, id int64) (Client, error)
	GetClients(ctx context.Context, arg GetClientsParams) ([]Client, error)
	GetPermission(ctx context.Context, id int64) (Permission, error)
	GetPermissions(ctx context.Context, arg GetPermissionsParams) ([]Permission, error)
	GetRequest(ctx context.Context, id int64) (Request, error)
	GetRequests(ctx context.Context, arg GetRequestsParams) ([]Request, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserPayment(ctx context.Context, id int64) (UserPayment, error)
	GetUserPayments(ctx context.Context, arg GetUserPaymentsParams) ([]UserPayment, error)
	GetUserRole(ctx context.Context, id int64) (UsersRole, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	GetUsersRoles(ctx context.Context, arg GetUsersRolesParams) ([]UsersRole, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPayment(ctx context.Context, arg UpdateUserPaymentParams) (UserPayment, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UsersRole, error)
}

var _ Querier = (*Queries)(nil)
