// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: roles.sql

package db

import (
	"context"
	"database/sql"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  name, createdby_id
) VALUES (
  $1, $2
)
RETURNING id, name, createdby_id
`

type CreateRoleParams struct {
	Name        string         `json:"name"`
	CreatedbyID sql.NullString `json:"createdby_id"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.Name, arg.CreatedbyID)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedbyID)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE 
FROM roles 
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, createdby_id FROM roles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedbyID)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, name, createdby_id FROM roles 
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedbyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles 
SET name = COALESCE($2,name)
WHERE id = $1
RETURNING id, name, createdby_id
`

type UpdateRoleParams struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole, arg.ID, arg.Name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedbyID)
	return i, err
}
