// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: user_payments.sql

package db

import (
	"context"
	"database/sql"
)

const createUserPayment = `-- name: CreateUserPayment :one
INSERT INTO user_payments (
  request_id, client_id, status
) VALUES (
  $1, $2, $3
)
RETURNING id, request_id, client_id, created_at, status
`

type CreateUserPaymentParams struct {
	RequestID sql.NullInt64 `json:"request_id"`
	ClientID  sql.NullInt64 `json:"client_id"`
	Status    PaidStatus    `json:"status"`
}

func (q *Queries) CreateUserPayment(ctx context.Context, arg CreateUserPaymentParams) (UserPayment, error) {
	row := q.db.QueryRowContext(ctx, createUserPayment, arg.RequestID, arg.ClientID, arg.Status)
	var i UserPayment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ClientID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const deleteUserPayment = `-- name: DeleteUserPayment :exec
DELETE 
FROM user_payments 
WHERE id = $1
`

func (q *Queries) DeleteUserPayment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPayment, id)
	return err
}

const getUserPayment = `-- name: GetUserPayment :one
SELECT user_payments.id, user_payments.client_id, user_payments.request_id, user_payments.status, clients.name, clients.preferred_payment_type, requests.title, requests.amount, requests.status 
FROM user_payments
JOIN clients ON user_payments.client_id = clients.id
JOIN requests ON user_payments.request_id = requests.id
WHERE user_payments.id = $1 LIMIT 1
`

type GetUserPaymentRow struct {
	ID                   int64          `json:"id"`
	ClientID             sql.NullInt64  `json:"client_id"`
	RequestID            sql.NullInt64  `json:"request_id"`
	Status               PaidStatus     `json:"status"`
	Name                 string         `json:"name"`
	PreferredPaymentType PaymentTypes   `json:"preferred_payment_type"`
	Title                string         `json:"title"`
	Amount               int64          `json:"amount"`
	Status_2             ApprovalStatus `json:"status_2"`
}

func (q *Queries) GetUserPayment(ctx context.Context, id int64) (GetUserPaymentRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPayment, id)
	var i GetUserPaymentRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RequestID,
		&i.Status,
		&i.Name,
		&i.PreferredPaymentType,
		&i.Title,
		&i.Amount,
		&i.Status_2,
	)
	return i, err
}

const getUserPayments = `-- name: GetUserPayments :many
SELECT user_payments.id, user_payments.client_id, user_payments.request_id, user_payments.status, clients.name, clients.preferred_payment_type, requests.title, requests.amount, requests.status 
FROM user_payments
JOIN clients ON user_payments.client_id = clients.id
JOIN requests ON user_payments.request_id = requests.id
ORDER BY user_payments.id
LIMIT $1
OFFSET $2
`

type GetUserPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUserPaymentsRow struct {
	ID                   int64          `json:"id"`
	ClientID             sql.NullInt64  `json:"client_id"`
	RequestID            sql.NullInt64  `json:"request_id"`
	Status               PaidStatus     `json:"status"`
	Name                 string         `json:"name"`
	PreferredPaymentType PaymentTypes   `json:"preferred_payment_type"`
	Title                string         `json:"title"`
	Amount               int64          `json:"amount"`
	Status_2             ApprovalStatus `json:"status_2"`
}

func (q *Queries) GetUserPayments(ctx context.Context, arg GetUserPaymentsParams) ([]GetUserPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPaymentsRow
	for rows.Next() {
		var i GetUserPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.RequestID,
			&i.Status,
			&i.Name,
			&i.PreferredPaymentType,
			&i.Title,
			&i.Amount,
			&i.Status_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPayment = `-- name: UpdateUserPayment :one
UPDATE user_payments 
SET status = $2
WHERE id = $1
RETURNING id, request_id, client_id, created_at, status
`

type UpdateUserPaymentParams struct {
	ID     int64      `json:"id"`
	Status PaidStatus `json:"status"`
}

func (q *Queries) UpdateUserPayment(ctx context.Context, arg UpdateUserPaymentParams) (UserPayment, error) {
	row := q.db.QueryRowContext(ctx, updateUserPayment, arg.ID, arg.Status)
	var i UserPayment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ClientID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}
